<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Include="Tomb4Plus\Furr\syntaxTREP.fln" />
      <EmbeddedResource Include="Tomb4Plus\Furr\syntaxEarly.fln" />
      <EmbeddedResource Include="Tomb4Plus\Furr\syntaxT4L.fln" />
      <None Remove="Tomb4Plus\Leikkuri\font_table.txt" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TombLauncher.Contracts\TombLauncher.Contracts.csproj" />
      <ProjectReference Include="..\TombLauncher.Core\TombLauncher.Core.csproj" />
    </ItemGroup>

</Project>
